Add test to zero decrement
CPP-KT/bigint-task pull request #3
Opened 2023-05-19 12:55 UTC by Pythonlover-1

2023-05-19 20:28 UTC, dedlocc requested changes
давай сделаем это отдельным тестом/тестами, а не пихать в существующие

2023-05-19 20:28 UTC, dedlocc commented on tests.cpp
> +  // 0 и 4294967295
это комментарий к PR, а не к коду, зачем он здесь?

2023-05-19 20:28 UTC, dedlocc commented on tests.cpp
> +  EXPECT_EQ(-1, post_c);
разве существует адекватная реализация бигинта, в котором `b` и `c` не эквивалентны? ну и в любом случае проверка их эквивалентности была бы отдельным тестом

2023-05-19 20:28 UTC, dedlocc commented on tests.cpp
> +  EXPECT_EQ(-1, post_b);
наверное хочется тогда аналогичный тест и для `++`?

2023-05-19 20:39 UTC, Pythonlover-1 commented on tests.cpp
> +  EXPECT_EQ(-1, post_b);
Он сделан в следующем pr)

2023-05-19 20:59 UTC, Pythonlover-1 commented on tests.cpp
> +  EXPECT_EQ(-1, post_b);
fixed

2023-05-19 21:01 UTC, Pythonlover-1 commented on tests.cpp
> +  // 0 и 4294967295
fixed

2023-05-19 21:01 UTC, Pythonlover-1 commented on tests.cpp
> +  EXPECT_EQ(-1, post_c);
fixed

2023-05-20 12:56 UTC, dedlocc requested changes
раздели на 2 теста

2023-05-20 15:17 UTC, dedlocc approved these changes

2023-05-20 15:18 UTC, merged