Add signed_comparisons, inc test
CPP-KT/bigint-task pull request #4
Opened 2023-05-19 20:14 UTC by Pythonlover-1

2023-05-19 20:41 UTC, dedlocc requested changes

2023-05-19 20:41 UTC, dedlocc commented on tests.cpp
> +  EXPECT_EQ(0, post_b);
это по логике скорее относится к #3

2023-05-19 20:41 UTC, dedlocc commented on tests.cpp
> +// И проходили вещи по типу 100 == -100
это по логике всё же коммент к PR, а не к коду, так что здесь его быть не должно

2023-05-19 20:41 UTC, dedlocc commented on tests.cpp
> +}
а давай, если такого ещё нет, добавим аналогичные тесты, проверяющие это при хранении в дополнении до двух (e.g. неравенство `-100` и `2^32 - 100`), причём стоит учесть вариант с хранением 64-битных чисел

2023-05-19 21:04 UTC, Pythonlover-1 commented on tests.cpp
> +  EXPECT_EQ(0, post_b);
fixed

2023-05-19 21:47 UTC, Pythonlover-1 commented on tests.cpp
> +}
Добавил тесты для сравнения -100 и 2^64 - 100, 2^32 - 100

2023-05-19 21:47 UTC, Pythonlover-1 commented on tests.cpp
> +// И проходили вещи по типу 100 == -100
fixed

2023-05-20 12:59 UTC, dedlocc requested changes

2023-05-20 12:59 UTC, dedlocc commented on tests.cpp
> +  big_integer b("18446744073709551516"); // (1 << 64) - 100
хмм, а почему именно строкой решил тут?

2023-05-20 13:17 UTC, Pythonlover-1 commented on tests.cpp
> +  big_integer b("18446744073709551516"); // (1 << 64) - 100
1) Я решил писать идейно так же, как в других тестах (e.g. and_signed2)
2) Я не особо придумал в каком типе делать такое вычисление, поэтому решил остановиться на конструкторе от строки)

2023-05-20 15:16 UTC, dedlocc commented on tests.cpp
> +  big_integer b("18446744073709551516"); // (1 << 64) - 100
Можно было бы просто `18446744073709551516u`, тип подходящий сам выберется

2023-05-20 15:40 UTC, Pythonlover-1 commented on tests.cpp
> +  big_integer b("18446744073709551516"); // (1 << 64) - 100
Ок, сейчас сделаю

2023-05-20 16:20 UTC, dedlocc commented on tests.cpp
> +  big_integer b("18446744073709551516"); // (1 << 64) - 100
Да необязательно уже было, не суть

2023-05-20 16:41 UTC, merged